/* eslint-env node */

import type { Config } from '@pandacss/dev'
import presetBase from '@pandacss/preset-base'

const production = process.env.NODE_ENV === 'production'

const config: Config = {
    presets: [],
    eject: true,
    theme: {
        extend: {},
        tokens: {
            colors: {
                transparent: { value: '#ffffff00' },
                background: {
                    primary: { value: '#fbfcfd' },
                    secondary: { value: '#f2f3f4' },
                    backdrop: { value: '#eeeff0' },
                    overlay: { value: '#f8f9fa' },
                    muted: { value: '#ecebea' },
                    inverse: { value: '#0a0a0d' },
                },
                text: {
                    primary: { value: '#0a0a0d' },
                    secondary: { value: '#17171a' },
                    tertiary: { value: '#3a3b3d' },
                    muted: { value: '#525253' },
                },
                border: {
                    primary: { value: '#dddddf' },
                    active: { value: '#babbbc' },
                },
                shadow: {
                    primary: { value: 'rgba(0, 0, 0, 0.1)' },
                    muted: { value: 'rgba(0, 0, 0, 0.05)' },
                },
                brand: {
                    primary: {
                        blue: { value: '#5779b8' },
                        green: { value: '#88cb68' },
                        yellow: { value: '#e9c815' },
                        red: { value: '#961d2a' },
                        teal: { value: '#aadbeb' },
                        purple: { value: '#d49ed2' },
                        orange: { value: '#dd5c3f' },
                        pink: { value: '#ffa9c3' },
                        gold: { value: '#f2e8b8' },
                    },
                    secondary: {
                        blue: { value: '#6b96e5' },
                        green: { value: '#a9dd71' },
                        yellow: { value: '#ffd817' },
                        red: { value: '#ba2333' },
                        teal: { value: '#c7ffff' },
                        purple: { value: '#e6abe3' },
                        orange: { value: '#dd5c3f' },
                        pink: { value: '#ffa9c3' },
                        gold: { value: '#e5d8b2' },
                    },
                },
            },
            fonts: {
                main: { value: 'Satoshi Var, var(--font-system)' },
                head: { value: 'InterVariable, var(--font-system)' },
                text: { value: 'IAWriterQ Var, var(--font-system)' },
                mono: { value: 'Geist Mono Var, var(--font-mono)' },
            },
            fontWeights: {
                main: { value: 400 },
                head: { value: 700 },
                thin: { value: 200 },
                light: { value: 300 },
                regular: { value: 400 },
                medium: { value: 500 },
                bold: { value: 600 },
                bolder: { value: 700 },
                black: { value: 800 },
                massive: { value: 900 },
            },
            spacing: {
                xs: { value: '2px' },
                sm: { value: '4px' },
                md: { value: '8px' },
                lg: { value: '12px' },
                xl: { value: '16px' },
                x2: { value: '24px' },
                x3: { value: '32px' },
                x4: { value: '48px' },
                x5: { value: '64px' },
                x6: { value: '96px' },
                x7: { value: '128px' },
                x8: { value: '256px' },
            },
            sizes: {
                xs: { value: '2px' },
                sm: { value: '4px' },
                md: { value: '8px' },
                lg: { value: '12px' },
                xl: { value: '16px' },
                x2: { value: '32px' },
                x3: { value: '64px' },
                x4: { value: '128px' },
                x5: { value: '256px' },
                x6: { value: '512px' },
                x7: { value: '1024px' },
                x8: { value: '1280px' },
            },
            fontSizes: {
                xs: { value: '0.8125rem' },
                sm: { value: '0.875rem' },
                md: { value: '1rem' },
                lg: { value: '1.25rem' },
                xl: { value: '1.5rem' },
                x2: { value: '2rem' },
                x3: { value: '3rem' },
                x4: { value: '4rem' },
                x5: { value: '5rem' },
                x6: { value: '6rem' },
            },
            lineHeights: {
                xs: { value: '0.8125' },
                sm: { value: '0.875' },
                md: { value: '1' },
                lg: { value: '1.25' },
                xl: { value: '1.5' },
                x2: { value: '2' },
                x3: { value: '3' },
                x4: { value: '4' },
                x5: { value: '5' },
                x6: { value: '8' },
            },
            letterSpacings: {
                xs: { value: '-0.05em' },
                sm: { value: '-0.025em' },
                md: { value: '0em' },
                lg: { value: '0.025em' },
                xl: { value: '0.05em' },
                x2: { value: '0.075em' },
                x3: { value: '0.1em' },
                x4: { value: '0.125em' },
                x5: { value: '0.15em' },
                x6: { value: '0.175em' },
            },
            radii: {
                full: { value: '100%' },
                xs: { value: '2px' },
                sm: { value: '4px' },
                md: { value: '8px' },
                lg: { value: '12px' },
                xl: { value: '16px' },
            },
            borderWidths: {
                none: { value: '0px' },
                xs: { value: '1px' },
                sm: { value: '2px' },
                md: { value: '4px' },
                lg: { value: '8px' },
                xl: { value: '16px' },
            },
            shadows: {
                none: { value: 'none' },
                xs: { value: '0px 1px 2px {colors.shadow.muted}' },
                sm: { value: '0px 1px 3px {colors.shadow.primary}' },
                md: { value: '0px 4px 6px {colors.shadow.primary}' },
                lg: { value: '0px 10px 15px {colors.shadow.primary}' },
                xl: { value: '0px 20px 25px {colors.shadow.primary}' },
            },
            durations: {
                none: { value: '0ms' },
                fast: { value: '0.08s' },
                normal: { value: '0.14s' },
                medium: { value: '0.22s' },
                slow: { value: '0.36s' },
                slower: { value: '0.58s' },
                slowest: { value: '0.94s' },
            },
            easings: {
                none: { value: 'none' },
                linear: { value: [0.25, 0.25, 0.75, 0.75] },
                ease: { value: [0.25, 0.1, 0.25, 1.0] },
                easeSmooth: { value: [0.48, 0.205, 0.295, 0.92] },
                easeIn: { value: [0.42, 0.0, 1.0, 1.0] },
                easeInQuad: { value: [0.55, 0.085, 0.68, 0.53] },
                easeInCubic: { value: [0.55, 0.055, 0.675, 0.19] },
                easeInQuart: { value: [0.895, 0.03, 0.685, 0.22] },
                easeInQuint: { value: [0.755, 0.05, 0.855, 0.06] },
                easeInSine: { value: [0.47, 0.0, 0.745, 0.715] },
                easeInExpo: { value: [0.95, 0.05, 0.795, 0.035] },
                easeInCirc: { value: [0.6, 0.04, 0.98, 0.335] },
                easeInBack: { value: [0.6, -0.28, 0.735, 0.045] },
                easeOut: { value: [0.0, 0.0, 0.58, 1.0] },
                easeOutQuad: { value: [0.25, 0.46, 0.45, 0.94] },
                easeOutCubic: { value: [0.215, 0.61, 0.355, 1.0] },
                easeOutQuart: { value: [0.165, 0.84, 0.44, 1.0] },
                easeOutQuint: { value: [0.23, 1.0, 0.32, 1.0] },
                easeOutSine: { value: [0.39, 0.575, 0.565, 1.0] },
                easeOutExpo: { value: [0.19, 1.0, 0.22, 1.0] },
                easeOutCirc: { value: [0.075, 0.82, 0.165, 1.0] },
                easeOutBack: { value: [0.175, 0.885, 0.32, 1.275] },
                easeInOut: { value: [0.42, 0.0, 0.58, 1.0] },
                easeInOutQuad: { value: [0.455, 0.03, 0.515, 0.955] },
                easeInOutCubic: { value: [0.645, 0.045, 0.355, 1.0] },
                easeInOutQuart: { value: [0.77, 0.0, 0.175, 1.0] },
                easeInOutQuint: { value: [0.86, 0.0, 0.07, 1.0] },
                easeInOutSine: { value: [0.445, 0.05, 0.55, 0.95] },
                easeInOutExpo: { value: [1.0, 0.0, 0.0, 1.0] },
                easeInOutCirc: { value: [0.785, 0.135, 0.15, 0.86] },
                easeInOutBack: { value: [0.68, -0.55, 0.265, 1.55] },
            },
            animations: {
                spin: { value: 'spin {durations.slower} linear infinite' },
                fadeIn: { value: 'fadeIn {durations.slower} {easings.easeIn}' },
                scrollX: { value: 'scrollX {durations.slower} linear infinite' },
                scrollY: { value: 'scrollY {durations.slower} linear infinite' },
                flickerX: { value: 'flickerX {durations.fast} linear infinite' },
                flickerY: { value: 'flickerY {durations.fast} linear infinite' },
                moveDown: { value: 'moveDown {durations.normal} {easings.easeIn}' },
                moveUp: { value: 'moveUp {durations.normal} {easings.easeIn}' },
                moveLeft: { value: 'moveLeft {durations.normal} {easings.easeIn}' },
                moveRight: { value: 'moveRight {durations.normal} {easings.easeIn}' },
                scaleIn: { value: 'scaleIn {durations.slowest} {easings.easeOut}' },
                scaleOut: { value: 'scaleOut {durations.slowest} {easings.easeIn}' },
            },
        },
        keyframes: {
            spin: {
                '0%': { transform: 'rotate(0deg)' },
                '100%': { transform: 'rotate(360deg)' },
            },
            fadeIn: {
                '0%': { opacity: 0 },
                '100%': { opacity: 1 },
            },
            scrollX: {
                '0%': { transform: 'translateX(0%)' },
                '100%': { transform: 'translateX(-100%)' },
            },
            scrollY: {
                '0%': { transform: 'translateY(0%)' },
                '100%': { transform: 'translateY(-100%)' },
            },
            flickerX: {
                '0%': { transform: 'translateX(0px)' },
                '100%': { transform: 'translateX(var(--move-x, -2px))' },
            },
            flickerY: {
                '0%': { transform: 'translateY(0px)' },
                '100%': { transform: 'translateY(var(--move-y, -2px))' },
            },
            moveDown: {
                '0%': { translate: '0% var(--move-y, -100%)' },
                '100%': { translate: '0% 0%' },
            },
            moveUp: {
                '0%': { translate: '0% var(--move-y, 100%)' },
                '100%': { translate: '0% 0%' },
            },
            moveLeft: {
                '0%': { translate: 'var(--move-x, 100%) 0%' },
                '100%': { translate: '0% 0%' },
            },
            moveRight: {
                '0%': { translate: 'var(--move-x, -100%) 0%' },
                '100%': { translate: '0% 0%' },
            },
            scaleIn: {
                '0%': { scale: 'var(--scale, 0.9)' },
                '100%': { scale: '1' },
            },
            scaleOut: {
                '0%': { scale: '1' },
                '100%': { scale: 'var(--scale, 0.9)' },
            },
        },
        breakpoints: {
            sm: '768px',
            md: '1024px',
            lg: '1312px',
        },
    },
    conditions: {
        extend: {
            ...presetBase.conditions,
        },
    },
    utilities: {
        extend: {
            ...presetBase.utilities,
            fillSpace: {
                className: 'fill-space',
                shorthand: 'fs',
                values: ['absolute', 'fixed'],
                group: 'Layout',
                transform: (value) => {
                    return {
                        position: value,
                        top: '0',
                        left: '0',
                        right: '0',
                        bottom: '0',
                        width: 'auto',
                        height: 'auto',
                    }
                },
            },
            layout: {
                className: 'layout',
                values: ['column', 'row'],
                group: 'Layout',
                transform: (value) => {
                    return {
                        display: 'flex',
                        flexDirection: value,
                        flexWrap: value === 'column' ? 'nowrap' : 'wrap',
                        alignItems: value === 'column' ? 'flex-start' : 'center',
                        justifyContent: 'flex-start',
                        minWidth: '0%',
                        maxWidth: '100%',
                        width: 'auto',
                    }
                },
            },
        },
    },
    patterns: {
        extend: {},
        column: {
            ...presetBase.patterns.flex,
            defaultValues: {
                direction: 'column',
                gap: '2',
                align: 'flex-start',
                justify: 'flex-start',
                wrap: 'wrap',
                minWidth: '0%',
                maxWidth: '100%',
                width: 'auto',
            },
        },
        row: {
            ...presetBase.patterns.flex,
            defaultValues: {
                direction: 'row',
                gap: '2',
                align: 'flex-start',
                justify: 'flex-start',
                wrap: 'wrap',
                minWidth: '0%',
                maxWidth: '100%',
                width: 'auto',
            },
        },
        fill: {
            ...presetBase.patterns.box,
            defaultValues: {
                width: '100%',
                height: '100%',
                top: '0',
                left: '0',
                position: 'absolute',
            },
        },
    },
    globalCss: {
        extend: {},
    },

    prefix: '',
    separator: '-',
    preflight: false,
    hash: {
        'cssVar': false,
        'className': true,
    },
    syntax: 'object-literal',
    lightningcss: false,
    jsxFramework: 'react',
    jsxStyleProps: 'minimal',
    include: ['./src/**/*.{js,jsx,ts,tsx,astro}'],
    exclude: [],
    importMap: '@/styles/system',
    outdir: 'styles/system',
    outExtension: 'js',
    clean: true,
    minify: production,
    watch: !production,
}

export default config
