name: Publish Rust

on:
  workflow_run:
    branches:
      - main
    workflows:
      - Tests & Checks
    types:
      - completed
  workflow_dispatch:

permissions: write-all

jobs:

  publish:

    name: Publish
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' && github.repository_owner == 'Systemcluster')}}

    outputs:
      tag: ${{ steps.publish.outputs.tag }}
      version: ${{ steps.publish.outputs.version }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - stable

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          submodules: recursive
          show-progress: false

      - name: Set up Rust
        uses: Systemcluster/actions@setup-rust-v0
        with:
          channel: ${{ matrix.toolchain }}
          cache-key-job: true

      - name: Publish crates
        uses: Systemcluster/actions@release-crates-v0
        id: publish
        with:
          crates-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: ${{ !secrets.CARGO_REGISTRY_TOKEN }}
          allow-dirty: true
          tag-crate: kitoken
